sanderslab/magellanmapper

docs/install.md
Addresses issue #3. Provide instruction on installing Sphinx and using the doc Bash build script to generate API docs. Fix a small grammatical typo.
=> Basic documentation on using the doc build script

README.md
Converted the atlas editor shortcuts written in list form into a table that is more easily readable and accessible in the README file.
=> Put atlas editor info into a tabular format in README

bin/build_deps.bat, bin/build_deps.sh, bin/build_jb.bat, bin/build_jb.sh, bin/build_se.bat, bin/build_se.sh, bin/setup_multi_venvs.bat, bin/setup_multi_venvs.sh, bin/setup_venv.bat, bin/setup_venv.sh, docker/buildse/Dockerfile, docker/ubuntu1604/Dockerfile, docker/ubuntu1604_venv/Dockerfile, docs/install.md, docs/release/release_v1.4.md, docs/settings.md, setup.py
Two key dependencies for MagellanMapper do not currently provide Python wheel packages and are not straightforward to build:
- SimpleElastix, built through Cmake and unable to be compiled through Pip (as far as I know)
- Javabridge, which requires a Java Development Kit to build when installing through Pip
To avoid requiring users to compile these packages themselves, we have provided custom wheels built on all three major OSes. Although we have scripts to build SimpleElastix, the process has consisted of several manual steps for each dependency. To limit the workload, we have built wheels only for Python 3.6 thus far.
Automating these builds would have several advantages:
- Enable more frequent updates to these dependencies as necessary
- Facilitate building for multiple Python versions, …
=> Automate dependency wheel builds to facilitate updates and expand Python version compatibility

magmap/gui/visualizer.py
Fixes #11 . The GUI has stripped extensions of registered images matching the filename of the given image to allow matching suffixes even if the extension differs. Without the atlas filename extension, however, SimpleITK cannot determine the file format to write when the atlas is saved through the GUI.
Since each registered suffix is tested for a potential match regardless of extension, use these found matches to populate the list of available registered images, preserving their extension. This change avoids the need to strip extensions while allowing the given suffix with its extension to be accessed directly.
=> Fix to store extension of loaded registered images via the GUI

docs/release/release_v1.4.md, run.py
Catch unhandled exceptions globally through the except hook. Log these exceptions to file, ideally using the existing logger file handler. In case this handler does not exist, also output to a standard Python temporary file path, which avoids the need to load libraries to identify the user app directory.
=> Log unhandled exceptions

bin/setup_pyinstaller.spec, magmap/gui/event_handlers.py, magmap/gui/visualizer.py, magmap/io/cli.py, magmap/io/importer.py, magmap/io/sqlite.py, magmap/settings/config.py
Detect Apple Events in PyInstaller builds when the app to open image files in the current window or a new app instance.
This PR provides two additional functionalities:
1. PyInstaller builds detect open document Apple Events such as those from Finder or dragging and dropping a file onto the app icon. These events are passed to the app on its startup as a command-line argument. While MagellanMapper interprets these leading arguments as image paths, those given through Finder are typically full image paths (eg `myvolume_image5d.npy`), rather than the original-based image paths (eg `myvolume.czi` or `myvolume.`) that the app normally expects. Apply the same image path deconstruction used within the GUI to identify and open these images given as command-line arguments, including those passed …
=> Open files by Apple Events

magmap/gui/plot_editor.py
Fixes #22. Occasionally an image set and channel combination will be requested that is not available, such as sub-ROI padding images in the ROI editor above or below the image, which only contain a background image. Check whether this image combo exists in the axes images for the plot.
=> Fix error when no axes image exists for the given image set and channel

magmap/atlas/ontology.py, magmap/io/np_io.py
Addresses issue mentioned in #26 when loading the `region_ids.csv` file included with the E18.5 atlas in the sample data.
The ID and region name columns in labels reference files have assumed the values in the Allen ontology/structure graph files. Support alternate keys using the `AtlasMetrics` enums used for output stats. Catch key errors when loading these files to avoid crash on startup when unable to parse the files.
=> Support alternate column names in labels reference files

magmap/io/importer.py
Fixes #28. Catch exceptions raised from Javabridge when it cannot find a Java home directory path, such as that set by a `JAVA_HOME` environment variable. Also, fix the docs' reference to the `JVMNoutFoundError` raised when Java cannot be initialized.
=> Fix error when unable to find Java home directory

docs/cli.md, magmap/atlas/transformer.py, magmap/io/cli.py, magmap/io/libmag.py, magmap/io/np_io.py, magmap/settings/config.py, magmap/settings/profiles.py, magmap/settings/roi_prof.py
The `--proc` command-line argument has supported only one argument at a time. This PR expands support for multiple tasks during the same command, each given as a separate string. For example, to both detect blobs and perform match-based colocalization, the command can be given as:
```
python run.py <image-path> --proc detect coloc_match
```
The arguments are parsed similarly to other arguments that may contain sub-arguments. This change allows integrating other sub-tasks into this parameter, such as the image preprocessing tasks. Previously, preprocessing needing to be supplied as such:
```
python run.py <image-path> --proc preprocess --roi_profile <profile-with-preprocess-setting>
```
which now simplifies to:
```
python run.py <image-path> --proc preprocess=rotate
```
for a rotation …
=> Support multiple processing tasks in the same command

magmap/atlas/edge_seg.py, magmap/settings/atlas_prof.py
Edge distance measuring is not required for the pipelines, but serves as a method of assessment. Allow this metric to be turned off through an atlas profile setting, which can save time during debugging or whenever the metric is not required.
For now, we will leave the option on for consistency with existing pipelines. Could consider turning it off by default since many workflows may not need it.
=> Option to turn off edge distance measuring

magmap/gui/visualizer.py, magmap/io/importer.py
RAW file import has been supported for multi-plane image files, but not yet for directories of single-plane image files. This PR extends RAW support to these individual files. It removes the assumption that these files can be read as standard image file types and allows the user to proceed with import after filling out shape and data type information if these cannot be extracted automatically. Even if the full shape cannot be determined automatically, the channels and number of planes is auto-populated based on the files in the directory.
Additionally, this PR fixes an issue where the import button was enabled after setting up import from a directory but shape and data type information were not complete.
=> Import raw single planes

magmap/io/importer.py, magmap/io/yaml_io.py, magmap/settings/profiles.py
Fixes #34.
This PR fixes loading metadata loaded in the prior, NPZ file format, when loaded directly, using the `--meta` command-line argument. File not found and Unicode errors are integrated directly into the YML load wrapper, and the file resaving as YML format is integrated into the metadata loader. Profiles loaded as YML files also catch load errors.
=> Fix updating metadata format

docs/cli.md, magmap/atlas/edge_seg.py, magmap/io/np_io.py, magmap/io/sitk_io.py
MagellanMapper uses "registered image suffixes" for two main purposes:
- Convenience when loading images that have been registered to another image, where the various registered images each have a different suffix (eg `atlasVolume` for the atlas intensity image registered to a sample image, `annotation` for the registered atlas labels image)
- Overlaying different types of images, such as the `atlas` type for the intensity image and `annotation` type for the labels image
These suffixes are accessed through the `--reg_suffixes` command-line flag or the "Intensity" and "Labels" selection controls in the "Registered Images" section of the GUI. Registered images are identified by a base image path to which these suffixes are appended. Filenames given in the GUI are deconstructed if possible …
=> Liberalize reg suffixes

magmap/io/importer.py, magmap/io/np_io.py
Fixes #43. This PR creates parent directories for output files of both single- and multi-plane file imports. This change prevents an error when outputting files to a new directory.
The PR also sets default resolutions of 1 for each physical dimension if no resolutions are set during import since resolutions are assumed to exist throughout MagellanMapper, and the default values of None lead to errors. These resolutions changes have been added to the image setup function since the GUI already handles default resolutions separately. An alternative would be to set the resolutions in the import functions themselves, but handling them earlier makes fewer assumptions in the importer.
=> Fix importing images to non-existing parent directories and without resolutions

docs/conf.py, magmap/io/cli.py, magmap/settings/config.py, setup.py
MagellanMapper was originally written with backward compatibility for Python 2.7 in mind, and type hints was one feature that we had not incorporated to maintain this compatibility. Instead, we specified data types in docstrings, which is unevenly supported in various static checkers and IDEs. MagellanMapper has gradually adopted more Python 3-specific features, however, and now that we are explicitly incorporating them, this PR introduces type hints into the codebase. Type hints will make data typing more explicit and improve support from static checkers.
Since much of the existing code has typing in docstrings, this PR starts by converting only the `magmap.io.cli` module to use type hints and the `typing` package. I also took the opportunity to update the module docstring by removing …
=> Type hints

magmap/cv/cv_nd.py, magmap/io/cli.py, magmap/io/export_stack.py, magmap/plot/plot_support.py
The image plane export task (`--proc export_planes`) outputs planes directly, without supporting any of the transformation CLI arguments or profile settings. The function for displaying multichannel images in Matplotlib figures supports the `--transform rotate` argument for  90 degree image rotations. This PR generalizes this support into a wrapper function for 90 degree rotation that defaults to rotation in the xy-plane to use in image plane export.
Additionally, it streamlines exported filenames to not add a plane index when exporting a single plane, such as for 2D images. To turn off the filename suffix (`_export[_i]`) entirely, the CLI `--suffix` argument (and same for `--prefix`) is fixed to accept empty strings.
=> Support rotation of exported image planes

magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/cv/cv_nd.py, magmap/cv/segmenter.py, magmap/settings/atlas_prof.py, magmap/settings/config.py, magmap/settings/profiles.py
This PR generalizes the adaptive erosion filter sizes used for generating watershed marker seeds markers to use these adaptive filter sizes during smoothing by morphological filters. When using this mode, the filters are now smaller when smoothing would lead to excessive changes in size compared with the original volume. This mode can be applied by changing the atlas profile `smoothing_mode` setting to `config.SmoothingModes.adaptive_opening` or `config.SmoothingModes.adaptive_erosion` for opening or erosion filters, respectively.
Additionally, the erosion filter size used prior to skeletonization in the marker generation step can be configured through the atlas profile `RegKeys.SKELETON_EROSION` setting. Sizes can range from 0 up, where 0 means that no erosion is applied, or `False` to …
=> Adaptive smoothing filter sizes and pre-skeletonization erosion configuration

.github/workflows/main.yml, envs/requirements.txt, magmap/cv/segmenter.py, magmap/gui/roi_editor.py
This PR sets up a basic continuous integration workflow with:
- Python 3.6-3.8 on Ubuntu
- Dependency installation
- Flake8 testing
- Unit testing
The workflow is based on the GitHub guide (https://docs.github.com/en/actions/guides/building-and-testing-python) and the default workflow template in the Actions tab.
=> Initial CI setup

docs/release/release_v1.5.md, magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/atlas/register.py, magmap/io/sitk_io.py, magmap/settings/atlas_prof.py
Addresses #51. Smoothing metrics have been measured when smoothing during atlas import, but not when smoothing after edge-aware reannotation (the `--register merge_atlas_segs` task). This PR extends those metrics to that task.
If metrics aren't needed, they can now also be toggled through an atlas profile setting, `meas_smoothing`. This PR adds a new profiled named `fewerstats` to turn off as many metrics as possible, right now just `meas_smoothing` and `meas_edge_dists`.
Also fixes #52. The metric may hang when using SimpleITK/SimpleElastix 2.0 because of apparent changes in how Python multiprocessing is handled. This PR sets SimpleITK to use the "Platform" threader to fix this hang on SimpleITK 2.0. The setting is not applied in earlier SimpleITK version since the setting does not …
=> Output smoothing metrics when merging segmentations and toggle smoothing metrics

.github/workflows/main.yml
The CI cache has been storing downloaded Python wheels but not the installation, which can take almost two minutes to complete. To reduce this redundancy, this PR caches and restores the full environment with settings recommended from here: https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
=> Cache full Python environment in CI workflow

magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/settings/config.py
DSC metrics between the original and new labels are measured and printed to console during the `merge_atlas_segs` tasks but not saved to file. Now that metrics from this task are saved (#54), this PR saves these labels-specific metrics as well. Additionally, the atlas to labels DSC metric already saved is fixed to use the new rather than the original labels.
=> Save more DSC metrics when in the merge atlas segmentations task

magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/cv/cv_nd.py, magmap/cv/segmenter.py, magmap/settings/roi_prof.py, magmap/tests/test_img_equality.py
The labels to markers erosion task, used for atlas lateral plane extension and edge-aware refinement, uses multiprocessing but has not supported the spawn start method required for Windows (see #58). This PR adds a fallback to support spawn mode by pickling each label region and distance weight map separately if not in fork mode. The pickling reduces performance slightly, but only the bounding box of each label is pickled rather than the whole image for each label.
This PR also adds a test module to check for the equality between two NumPy arrays, useful for checking whether the image output is the same in fork vs spawn mode.
=> Support spawned multiprocessing when eroding labels to markers

docs/release/release_v1.4.md, magmap/atlas/atlas_refiner.py, magmap/atlas/transformer.py, magmap/cv/chunking.py, magmap/cv/detector.py, magmap/cv/segmenter.py, magmap/cv/stack_detect.py, magmap/gui/visualizer.py, magmap/io/df_io.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/stats/clustering.py, magmap/stats/vols.py, magmap/tests/test_chunking.py
Multiprocessing in MagellanMapper has assumed the forked start method, where objects present before the fork are available to each child process. Python on Windows only supports the spawn start method, however, where objects need to be shared through other means such as pickling or shared memory arrays. PR #59 introduced support for Windows in the labels erosion to markers task through pickling, but pickling can be slow enough to obviate the performance improvements of multiprocessing in other tasks such as converting labels to edges.
This PR uses shared memory arrays instead of pickling to share large objects. A new class handles conversion to and from the shared array for NumPy arrays, which the classes used for multiprocessing can extend to convert their arrays if not present through …
=> Use shared memory arrays for spawned multiprocessing

magmap/gui/visualizer.py, magmap/io/importer.py, magmap/io/libmag.py
This PR makes several fixes/updates to the "Registered Images" selectors in the GUI:
- Supports finding suffixes with known multiple extensions (eg `.nii.gz`; fixes #63; also fixes a scenario related to #26)
- Hides the extension while remembering it for loading/saving images
- Fixes loading images in the GUI while displaying an image with a registered intensity image set
=> Registered image selector fixes

docs/release/release_v1.5.md, magmap/gui/vis_handler.py, magmap/gui/visualizer.py
The TraitsUI library stores and restores window size and position in a preferences database. This PR enables that database by applying an ID to the main GUI View, which triggers saving these preferences (see [docs](https://docs.enthought.com/traitsui/api/traitsui.view.html#traitsui.view.View.ui)). The database is also manually generated since it is not automatically created when the parent directories are not present.
This PR also allows window widths to be decreased more and makes the default width smaller. Previously, the window width could not be decreased below the initial size, which was larger than some screens (1500 px). Now the default size is 1200 px to fit into 720p screens, and the window can be further decreased to a narrow width if desired. The preferences also save the …
=> Window size and position preferences

magmap/atlas/ontology.py, magmap/atlas/register.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/stats/atlas_stats.py
Main image setup supports loading labels reference files given as either CSV (to data frame) or JSON (to dict) format, but many other functions have expected JSON format. Extend support for CSV format by creating a simple wrapper function to convert labels reference files from either data frames or dict to lookup references. Volume stats, region export, and region development now support CSV in addition to JSON reference files.
=> Generalize the labels reference lookup for data frames

magmap/gui/vis_handler.py, magmap/gui/visualizer.py, magmap/io/cli.py, magmap/io/libmag.py, magmap/settings/profiles.py, setup.py
The profiles tab contains dropdown selectors for ROI, atlas, and grid search profiles, but currently it provides little guidance on selecting a profile without having to look into the source code. This PR adds profile previews, where selecting a profile shows the profile contents in a new text area. The profile is simply the dictionary pretty-formatted to show the settings keys and value pairs.
Previously loading new profiles required pressing the "Load profiles" button, which may be unintuitive since the "Add profile" could also be interpreted to fully add it. This PR removes the "Load profiles" step so that pressing the "Add" button adds it to the table and sets it up. The "Load profiles" button is renamed to "Rescan" and now serves only to rescan the `profiles` directory to find any …
=> Add profile previews and basic settings sub-panel

magmap/atlas/atlas_refiner.py, magmap/io/export_stack.py, magmap/io/np_io.py, magmap/stats/atlas_stats.py
The `--proc extract` tasks exports an individual plane to a single file, while the `--proc animated` tasks exports multiple planes (eg the whole image stack) to an animated format such as and animated GIF or MP4 file. This PR extends the former task by allowing multiple planes to be extracted to separate files.
This addition comes in handy when building a collage of image from multiple images. Previously, each image is loaded, with one plane extracted per image and collected into a collage. To export multiple collages, eg for different planes in each image, the images must be reloaded for each plane. This update extracts all planes for each image, greatly reducing load time.
The multiprocessing that handles this tasks has also been extended as in #60 to support spawned multiprocessing, …
=> Export image stacks to multiple figures, support Windows

bin/build_bf.sh, docs/release/release_v1.5.md, magmap/io/importer.py, setup.py
The Python-Bioformats dependency has been pinned in MagellanMapper to v1.1.0 because of a heap space error encountered with later versions of the package when importing some large image files (see https://github.com/CellProfiler/python-bioformats/issues/95). Since the Bio-Formats library included in this version of the package is relatively old (Bio-Formats v5.1.8 from 2016), this PR updates the package to bring in the current Bio-Formats version (v6.6.0). The library was tested on a large (40GB), multi-series CZI file that previously could not be loaded because of a JPEG-XR not supported error but now loads with this new library.
Python-Bioformats now depends on a fork of the original Javabridge package, named Python-Javabridge, pinned to its latest version. This latest version in turn …
=> Update Python-Bioformats dependency version

clrstats/R/jitter_plot.R, clrstats/R/volcano_plot.R, magmap/atlas/atlas_refiner.py, magmap/atlas/register.py, magmap/io/sitk_io.py, magmap/settings/config.py
Image registration provides a fallback in case the registration does not complete, typically because Elastix does not find enough overlap between the fixed and moving image. The fallback matches the world info (ie spacing, direction, and origin) between the two images in case the underlying images are close enough to match, but their metadata is shifting them apart.
PR #36 inadvertently introduced a change where the spacing was excluded from this world info match, but occasionally this change is necessary to find the appropriate match. This PR extends this behavior by keeping one fallback registration where direction and origin are matched but spacing is left the same, then adding another fallback where all world info is changed. As a final fallback, the atlas is now simply returned as-is …
=> Add more fallback image registration setups

magmap/gui/plot_editor.py, magmap/gui/visualizer.py
PR #76 fixed persistence of both auto and manual intensity settings in the image adjustment panel, but opacity, brightness, and contrast settings are still reset when scrolling through images. This PR makes these settings persistent while scrolling through a given image.
Additionally, the brightness and contrast settings have conflicted with one another, where adjusting one caused the other setting to be ignored. The brightness and contrast settings both operate on the original image, meaning that they need to know any changes to the other setting to reapply it when making any adjustments. This PR fixes the settings by applying both brightness and contrast together with any change to one value.
=> Fix persistence of more image adjustment settings: brightness, contrast, and opacity

docs/release/release_v1.5.md, magmap/gui/import_threads.py, magmap/io/cli.py, magmap/io/importer.py, magmap/settings/config.py, magmap/settings/logs.py
Errors that occur during image import have shown only limited feedback in the GUI, requiring the user to view the console or the log file to see more detailed error messages (see #82). For those using the installer version, the log file is not intuitive to locate. This PR provides more feedback in the GUI by reporting any error messages in the import feedback text area along with the path to the log file for more detailed info such as the stack trace.
A common source of import errors is importing a directory that may contain other, non-image files. This PR now simply skips individual file planes that give an error. To report the log path after errors that stop the import, the path is now stored in `config` after setting up the log path with any file rotation.
=> Provide more error feedback during image import in the GUI

docs/cli.md, docs/release/release_v1.5.md, environment.yml, envs/environment_light.yml, magmap/io/cli.py, magmap/io/libmag.py, magmap/io/np_io.py, magmap/settings/config.py, magmap/tests/test_img_equality.py, setup.py, stitch/mesospim_to_tif.py, stitch/tile_config.py
The file importer in MagellanMapper uses a mixture of Python-Bioformats, Javabridge, Scikit-image, and NumPy itself to import files from commercial and open formats into NumPy arrays. To facilitate interoperability with other platforms, this PR adds support to export NumPy arrays to TIF format using the `tifffile` library.
The new `np_io.write_tif_file` function takes a NumPy array such as the current main image in 5D (`TZYXC` dimension order) format and exports it via `tifffile` to the default TIF format. Each channel is exported as a separate TIF file. The export can also be accessed through the CLI using the `--proc export_tif` task, which converts the file loaded as the main image to a TIF file(s) with a corresponding filename(s).
One use-case for exporting TIF files is to convert RAW …
=> Export files to TIF, including mesoSPIM RAW file import/export

docs/release/release_v1.5.md, magmap/gui/visualizer.py
The Profiles tab contains a table showing the currently loaded tables. Although profile entries can be removed by pressing Backspace/Delete on the selected row, the loaded profiles are not updated.
This PR adds a handler so that removing rows triggers updating all loaded profiles. The table is also now configured to allow dragging rows to rearrange the order of entries. These moves likewise trigger reloading the profiles automatically.
=> Edit loaded profiles in the profiles table

docs/release/release_v1.6.md, magmap/io/export_stack.py
The `--proc export_planes` task exports raw, unfiltered image planes, in contrast to `--proc extract`, which exports planes that have been overlaid and processed through Matplotlib. The export planes task has thus far been limited to exported individual planes for an entire volumetric image.
This PR adds the ability to specify the range of planes to export or an ROI to export as planes within it. The plane range can be specified using the `--slice start,stop,step` command-line argument, and the ROI through the `--offset x,y,z --size x,y,z` syntax. These options mimic the range and ROI settings used for extracting processed planes and uses the same underlying machinery.
We at some point may need to change the task names to distinguish them better!
=> Option to specify the plane range or ROI when exporting raw planes

docs/release/release_v1.6.md, magmap/gui/plot_editor.py, magmap/gui/visualizer.py, magmap/plot/plot_support.py
Currently, image alignment can be assessed by adjusting the opacity of each image. This reduction in opacity allows the underlying image to be seen but also reduces the visibility of the overlying image, and the two images can be difficult to distinguish even when using different colors. Inspired by [here](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb), this PR adds an alpha blending model where only the overlapping parts of each image are blending, while the non-overlapping parts are left at full opacity. The non-transparent, non-overlapping parts thus provide high contrast between the overlying and underlying image as well as to the translucent, overlapping parts.
To identify the overlapping regions, this model relies …
=> Option to alpha blend overlaid images to highlight overlap and alignment

docs/release/release_v1.6.md, magmap/cv/segmenter.py, magmap/gui/visualizer.py
Fixes #91. This PR uses the new location for the watershed function Scikit-image. I also updated tooltips for the ROI Editor options and blob scaling as mentioned in #87.
=> Fix blob segmentation

docs/release/release_v1.6.md, docs/viewers.md, magmap/gui/roi_editor.py, magmap/gui/visualizer.py, magmap/io/df_io.py, magmap/settings/config.py
The GUI tools have many functions that are not inherently obvious, such as shortcuts that are not shown in the GUI or tooltips that only appear when hovering over specific GUI elements. As a first step to making documentation more accessible, this PR adds buttons to open the ReadTheDocs documentation in an external browser.
Specifically, this PR adds buttons to the ROI and Profiles panels to open the docs pages specific to these controls. The buttons open the pages through the Qt `QDesktopServices.openUrl` function, which opens the links in the default browser. Qt also provides the functionality to open the links directly in the app itself, but this would require making the `PyQtWebEngine` package a dependency.
TraitsUI also supports displaying basic HTML pages `QTextBrowser`. Future PRs …
=> Buttons to open help documentation in external browser

docs/release/release_v1.6.md, magmap/cv/colocalizer.py, magmap/cv/detector.py, magmap/io/sqlite.py
Blob verification and resaving ROIs triggered errors related to the blob matching introduced in v1.5, even when not performing blob matches. This PR fixes those errors.
=> Fix blob verification and resaving from blob match errors

docs/release/release_v1.6.md, magmap/atlas/labels_meta.py, magmap/atlas/transformer.py, magmap/gui/visualizer.py, magmap/io/importer.py, magmap/io/libmag.py, magmap/io/np_io.py
This PR rounds up a number of changes:
- Extension in main image paths are normally stripped when converting the paths to MagellanMapper-specific paths. This removal would also strip multiple path parts after periods, however, such as converting `MyFile.1.czi` to `MyFile`. Now only the final extension will be removed, and paths given by the `--prefix <path>` CLI argument do not undergo any stripping.
- Image metadata has been loaded into the global environment and discarded. Now the metadata is stored in the `Image5d` object to access more of the metadata and encapsulate it with the image. This change is part of the longer term plan to not store the metadata globally. One application of this storage is that metadata from an image can be loaded even if the image itself is not.
- …
=> Roundup to fix removing filenames after periods, store image metadata in image object, add control for default blob label

docs/release/release_v1.6.md, magmap/cv/colocalizer.py, magmap/cv/verifier.py, magmap/io/cli.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/settings/config.py
Match-based object colocalization has assumed that the whole image was available for blob detection, but the colocalization depends only on the detected blobs, not the image. By providing an option to perform the colocalization without the image, this task could be performed afterward, such as in a local computer that does not have the large main image.
This PR allows performing this colocalization without the image so long as its metadata file is present. When a main image is not loaded, a registered image has been loaded instead if present, but this image typically has different resolutions than the main image and is no longer loaded during this task. As a side effect, the image loader was also restructured to not attempt re-importing an image file if the main image was not loaded, …
=> Allow match-based colocalization when the full main image is not available

docs/conf.py
The API docs have not been built for the ReadTheDocs documentation because the RST files are not generated by default. As inspired by this [wokaround](https://github.com/readthedocs/readthedocs.org/issues/1139#issuecomment-398083449), this PR adds a configuration step to generate the RST files automatically when ReadTheDocs builds the documentation. Additionally, intersphinx links have been updated for Scipy, Matplotlib, and Pandas.
=> Build API docs for ReadTheDocs

docs/release/release_v1.6.md, magmap/io/df_io.py, magmap/io/export_regions.py, magmap/io/sqlite.py
Loading match-based blob colocalizations from the database can be very slow since blobs are extracted in batches to avoid exceeding the maximum number of parameters in a `SELECT` query statement. The max number was [limited](https://www.sqlite.org/limits.html) to the default for earlier versions of Sqlite3, but it turns out that the number is set by the compilation and may differ from the default. In testing on Python 3.8.8, for example, the limits is much higher than the 999 default in SQLite < 3.32.0. Using small batch sizes requires more batches and slows down performance considerably.
To maximize the batch size without exceeding it, this PR starts with a large batch size and recursively decreases this size if SQLite raises an error. User feedback is also provided in the console to …
=> Fix performance issue when loading large numbers of blob matches from the database

docs/release/release_v1.6.md, environment.yml, envs/environment_light.yml, magmap/io/cli.py, magmap/io/importer.py, magmap/io/np_io.py, magmap/settings/config.py, setup.py, stitch/mesospim_to_tif.py
We have required importing image files to convert them to NumPy format, which allows lazy loading large files through memory mapping. This loading allows large files to be loaded with limited RAM, but it also requires the extra time and file space for the file import. The main goals of this PR are to provide a mechanism to lazy load common image files (ie TIFs) while requiring neither prior import nor a major overhaul of image arrays.
As a way to bypass this import requirement for at least some image files, this PR uses the Tifffile library to memory map certain TIF images, loading them similarly to NumPy archives but without this import step. This loading supports TIFs that Tifffile can memory map, which are those with [contiguous …
=> Read TIF files directly with lazy loading through Tifffile

docs/release/release_v1.6.md, magmap/cv/chunking.py, magmap/cv/colocalizer.py, magmap/cv/stack_detect.py, magmap/cv/verifier.py, magmap/gui/visualizer.py, magmap/io/libmag.py, magmap/io/np_io.py
This PR address a couple issues:
- Fixes display of colocalizations in the GUI when the given ROI does not have any colocalizations
- Increases the overlap of blocks when finding matching blobs for colocalizations in large images since the matches are primarily detected with a smaller "inner ROI," which caused many colocalizations in the rest of the ROI to be missed
A couple additional changes:
- Fixes to import TIF files during the `import_only` task rather than simply opening the file
- Reduces repetitive logging during colocalization by logging blob verification parameters only when they change
=> Fix displaying colocalizations when none are present in an ROI and increase block overlaps when matching blobs

docs/release/release_v1.6.md, magmap/atlas/ontology.py, magmap/cv/colocalizer.py, magmap/cv/detector.py, magmap/gui/vis_3d.py, magmap/gui/visualizer.py, magmap/io/df_io.py, magmap/io/np_io.py
The GUI has assumed that the user wants to detect cells in all currently displayed channels. Sometimes the user may wish to detect cells in one channel while viewing other channels for reference, however. Cells may also have been detected in a prior, large image processing run while displaying these detections on the smaller, downsampled image used for image registration. This image typically only has one channel, and the GUI currently does not allow picking cells from the other channels.
This PR fixes this issues by adding a channel selector in the detection panel to specify the channels for cell detection. The user can unselect channels that are displayed or select channels that are not currently shown. When loading detections, the GUI adds channel choices based on all the loaded cells …
=> Detect blobs in any channel in the GUI

docs/release/release_v1.6.md, magmap/cv/colocalizer.py, magmap/io/sqlite.py
Blob match selection has been slowed by several factors:
- Initial blob selection
- Blob match selection on blob IDs, which requires batch processing because of the large number of IDs for the select parameters
- Redundant blob selection for each blob ID in the resulting blob matches
This PR improves selection performance by unifying these steps, removing redundant selections, and selecting in bulk:
- Select blobs as an inner join on the blob match selections
- Convert blobs to the blob match data frame format in bulk rather than match-by-match
- Filter by ROI parameters as an option rather than selecting these blobs first
We have seen blob match loading time improvements down from 6 min to 1 min. The prior blob match and ROI-parameter blob selection selection functions have been …
=> Improve retrieval times for match-based colocalizations

magmap/io/export_stack.py
Fixes #110. Matplotlib < 3.4 provided a deprecation warning that `Figure.add_subplot` would generate a new `Axes` object instead of reusing an existing object when given identical arguments. Animation needs to reuse the same `Axes` object and had relied upon `add_subplot` to deliver it, but later versions of Matplotlib generated these animations with a blank image until the final frame. Fix by simply retaining the `Axes` object and reusing it directly.
=> Fix regression in generating animation

docs/release/release_v1.6.md, magmap/io/export_regions.py, magmap/io/importer.py, magmap/io/np_io.py
Fixes #47. Creating a density map has loaded in a registered labels image to use as the output shape. The shape parameter has allowed specifying this output shape, the registered image has still been used in finding the scaling between the blobs and output image. Now that the blobs archive contains the size and resolutions from the original image, use this info when available to determine the scaling. When a shape argument is also present, bypass loading the registered image.
Future implementations could consider removing the pathways loading the `scale` and `target_size` values to find the original image now that the blobs stores this info.
=> Use image metadata in blobs instead of registered image for density map if available

docs/release/release_v1.6.md, magmap/gui/visualizer.py
Changing the min slider manually has not unchecked the Auto box initially because the change was ignored. When the min/max sliders are matched to the current image, any changes triggered by these sliders are flagged to be ignored, and the flag is reset. If the new min/max value is the same as the current value, the flag was not reset until the user made multiple manual changes to the slider. Fix by setting this flag only when the min/max values are changed from their current values.
=> Fix to uncheck Auto when manually changing the min intensity slider

docs/cli.md, docs/release/release_v1.6.md, magmap/io/export_stack.py, magmap/settings/config.py
Resizing the main image when exporting a stack has assumed that the resizing should use interpolation. While this behavior is often appropriate for intensity images, users may wish to change the type of interpolation or even turn it off, particularly if the image is a heat map. This PR adds a `--transform interpolation=<n>` CLI argument, where `n` = the interpolation order values in Scikit-image's [`transform.resize`](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize) function.
=> Configure the interpolation order when exporting a stack

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/settings/config.py
We are starting to add more registered image types to allow the user to configure which registered images are used for various tasks, such as the masks used for registration itself. This PR adds a `density` type to specify the density or heat map used when measuring the number of nuclei/cells in each atlas region.
=> Add a registered image type for density images and use for volume stats

docs/release/release_v1.6.md, magmap/gui/plot_editor.py, magmap/io/export_stack.py, magmap/plot/plot_support.py, magmap/settings/roi_prof.py
The ROI profile has allowed the user to toggle a colorbar displayed in the Plot Editor and when exporting a stack. This PR adds the following features:
- Changes the profile setting from a simple boolean to a dictionary that takes the arguments used in the Matplotlib [colorbar](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.colorbar.html) function
- The colorbar now updates when adjusting the intensity min/max sliders
- The colorbar is no longer repeated when exporting an animation
=> Configure colorbar in profile

magmap/cv/colocalizer.py, magmap/cv/detector.py, magmap/gui/visualizer.py, magmap/plot/plot_3d.py
Image regions that are largely empty often have the same upper and lower intensity percentiles, leading to a division by 0 error when saturating the ROI. While this scenario does not occur as frequently in microscopy images because of ambient noise, it occurs more often with heat maps. Blob detection has skipped this saturation step, but the 3D viewer attempts saturation during preprocessing, leading to a `Contour` error because of the NaN "saturated" ROI. This PR fixes this error and other potential NaN saturations by skipping the saturation if the intensity percentiles are the same.
Blob detection in the GUI also led to an error during logging when no blobs were detected, also fixed here.
=> Fix preprocessing largely empty ROIs

docs/release/release_v1.6.md, magmap/cv/colocalizer.py, magmap/cv/detector.py, magmap/cv/stack_detect.py, magmap/cv/verifier.py, magmap/gui/roi_editor.py, magmap/gui/visualizer.py, magmap/io/export_regions.py, magmap/io/export_rois.py, magmap/io/np_io.py, magmap/io/sqlite.py
Blob detections have been represented in MagellanMapper as a 2D NumPy array. The array's columns grew from `z, y, x, radius` to include `truth_flag, confirmation_flag, channel` and later `abs_z, abs_y, abs_x`. While accessing columns started with indexing these known positions, it was inherently error-prone because the indices were numeric rather than named, and the number of columns in the array could change based on the current task or if older versions of the blobs were loaded. Eventually, blobs column accessor functions were added, which used "standard" column indices so that they would not need to be remembered by index value. They assumed that the blob columns were set up to "standard" format, however, and did not allow flexibility in the number of columns. This lack of flexibility …
=> Make blobs columns flexible and encapsulated

magmap/cv/cv_nd.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/io/sitk_io.py, magmap/plot/plot_2d.py
MagellanMapper has generally expected 3D+ images, leading to errors when loading 2D images because of the expected z-axis. This PR adds more support for 2D images in several areas:
- 2D registered images are converted to single-plane 3D images when loading them in the GUI
- nD rotation now accepts 2D images
- Density map generation also takes 2D images
- Some refactoring for 2D plot tasks
=> More 2d support

clrstats/DESCRIPTION, clrstats/R/clrstats.R, clrstats/run.R, docs/release/release_v1.6.md, magmap/plot/plot_2d.py, magmap/plot/plot_support.py, magmap/settings/config.py
Clrstats has expected means test to output a single estimate, but independent t-tests output estimates for both groups. This PR fixes this issue by simply setting the raw effect as the difference of means and also computes a standardized effect using Cohen's d as implemented in the ~~`rstatix`~~ `effectsize` package.
- ~~Fixed confidence intervals to use the raw effect in case a standardized effect is also computed~~ Confidence intervals for effect sizes are now reported as absolute rather than relative values as these values are more likely expected and correspond to the direct stats output. MagellanMapper adds a `--plot_labels err_col_abs=<col>` sub-argument to plot these values since Matplotlib requires absolute values to be converted to relative values. The …
=> Fix computing independent t-test in Clrstats

docs/release/release_v1.6.md, magmap/plot/plot_2d.py, magmap/plot/plot_support.py, magmap/settings/config.py, setup.py
Swarm plots show each data sample as a separate point, with points spaced to avoid overlap. These plots are [implemented here in Seaborn](https://seaborn.pydata.org/generated/seaborn.swarmplot.html), and they incorporate additional functionality from the bar plots task such as x-tick scaling and vertical span groups.
Many of the Seaborn plot functions take data in long rather than wide format, whereas our bar plots have expected wide format. For consistency with Seaborn, our swarm plot wrapper takes long format. We may consider shifting to long format for all plot tasks if it simplifies/clarifies our data handling and call signatures.
- Added `--plot_labels vspan_format=<str>` to specify the format for vertical span labels.
- Setting scientific notation on incompatible …
=> Add swarm plots

.gitignore, docs/release/release_v1.6.md, docs/settings.md, magmap/gui/visualizer.py, magmap/io/cli.py, magmap/io/yaml_io.py, magmap/plot/plot_2d.py, magmap/plot/plot_3d.py, magmap/settings/config.py, magmap/settings/grid_search_prof.py, magmap/settings/prefs_prof.py, magmap/settings/profiles.py, magmap/stats/mlearn.py, magmap/tests/test_libmag.py, magmap/tests/test_visualizer.py, setup.py
MagellanMapper [stores settings](https://magellanmapper.readthedocs.io/en/latest/settings.html) in a variety of ways, but most GUI settings are not saved automatically. This PR uses the existing `SettingsDict` profiles class to store user preferences, starting with GUI state.
Profiles have been built on dictionaries, with additional methods to support updating from sub-profiles and saving to YAML files. A drawback of using dicts, however, is that keys had to be managed manually, either through strings or by using Enums. To simply this handling and to make data access safer, we are starting to convert these profiles from dicts to data classes. By using data classes, settings can be defined as attributes, with fields predefined and typing specified.
To ease migration, we will first add …
=> Save and restore preferences

docs/release/release_v1.6.md, magmap/gui/visualizer.py, magmap/io/np_io.py
This PR contains a bunch of fixes:
- Error window when moving the atlas level slider before a 3D image has been rendered
- Resets the labels reference file path when reloading an image in the GUI
- Fixed saving blobs in an ROI using the first displayed ROI or after moving the sliders without redrawing
- Fixed to store the image path when loading a registered image as the main image, which fixes saving the experiment name used when saving blobs
- Fixed loading blobs in the GUI when blob matches are present but without coordinates
=> Fixes roundup for GUI, image loading

magmap/atlas/ontology.py, magmap/atlas/register.py, magmap/gui/atlas_editor.py, magmap/gui/atlas_threads.py, magmap/gui/plot_editor.py, magmap/gui/vis_handler.py, magmap/gui/visualizer.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/io/sitk_io.py, magmap/plot/plot_support.py, magmap/settings/config.py, magmap/tests/test_img_equality.py, magmap/tests/test_visualizer.py
Here are several atlas navigation tools that I keep find myself needing:
- Region names are now entered automatically into the region navigator. Since the list is so long for atlases with many regions, it also has auto-complete so you can start typing in the name to bring it up quickly. Selecting a region brings you to it immediately, but you can check the "Append" option to build up multiple regions before navigating to them when unchecking the box.
- The atlas level slider now adjusts the atlas level at which regions are displayed when hovering over them in the viewers
- Next to the slider is a `Remap` button to remap the atlas labels to the selected level. This operation can take some time, so I have put it in a separate thread and added a progress bar to the status bar to remapping …
=> Populate the region selector with atlas label names, remap atlas levels, and prompt before redrawing edited viewers

README.md, bin/setup_venv.sh, docs/release/release_v1.6.md, environment.yml, envs/environment_light.yml, magmap/stats/clustering.py, setup.py
Scikit-learn, Boto3, and AWS CLI are not core dependencies and therefore can be moved to become optional.
- Pip installs: The `all` groups remains functionally the same, while a new `most` group is like `all` but without the above packages. The `setup_venv.sh` script now uses the `most` group by default.
- Conda installs: The above packages have been removed.
In either case, the packages can be installed manually by `pip` afterward.
=> Make Scikit-learn and AWS-related dependencies optional

magmap/settings/grid_search_prof.py, magmap/stats/mlearn.py
Fixes a regression where Python 3.6 cannot import `annotations`. This `__future__` feature was only added in Python 3.7. As a workaround, remove these imports and replace the type hints with string literals.
=> Fix error importing `annotations` in Python 3.6

docs/release/release_v1.6.md, setup.py
Fixes #130. The `imagecodecs` library is an optional dependency for `tifffile` but now leads to an error when loading `skimage.io` as of Tifffile v2022.7.28. This package is also required to load some types of single-plane images.
Note that the Conda `tifffile` package installs `imagecodecs` as a dependency. We won't add it to the Conda environment script since we don't import `imagecodes` directly, but only through Tifffile.
=> Add `imagecodecs` as a dependency

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/cv/cv_nd.py, magmap/gui/atlas_editor.py, magmap/gui/roi_editor.py, magmap/gui/visualizer.py, magmap/io/sitk_io.py, magmap/plot/plot_support.py, magmap/settings/atlas_prof.py
The Atlas Editor currently has three views to show 3D images. The order of these views has been fixed as `z`, `y`, and `x` moving clockwise from the left. The left view is the largest, taking up the full vertical space, while the right views are split into upper and lower views. Some images lend happen to lend themselves to a large z-plane in the left view, while others may show a small image there while compressing a larger image in one of the right views.
This PR adds dropdown selectors for the user the select the planes shown in each of the views:
- Each view has a separate dropdown in the ROI panel to select the plane to show in that view
- Selecting a plane currently selected in another dropdown swaps those selection automatically
- A blank option for each view turns off the view and …
=> Plane selectors for the plots in the Atlas Editor

.github/workflows/main.yml, docs/release/release_v1.6.md, magmap/cv/detector.py, magmap/gui/atlas_editor.py, magmap/gui/plot_editor.py, magmap/gui/roi_editor.py, magmap/gui/verifier_editor.py, magmap/gui/visualizer.py, magmap/plot/plot_3d.py, magmap/plot/plot_support.py, magmap/tests/test_detector.py
The ROI Editor provides tools to flag blobs as different classes by showing all the blobs within a given region of interest, but it may also be useful to view and adjust blob classes individually. This PR adds a viewer that displays blobs in separate subplots arranged as a grid. The user can click on each subplot to change the blob's classification and scroll to additional pages of blobs. Blobs are synchronized with the blobs table and can be saved to the database using the existing save blobs button.
=> Verifier viewer to adjust or confirm classifications

docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/register.py, magmap/atlas/transformer.py, magmap/cv/cv_nd.py, magmap/io/sitk_io.py, magmap/settings/atlas_prof.py, magmap/settings/config.py, magmap/tests/test_cv_nd.py
Image registration often requires atlas transformations. Currently, the registration entry point applies each transformation in several steps, including the atlas transformer, arbitrary rotation, and rescaling. Custom registration pipelines often skip this entry point, using the core registration function instead, but must handle transformations manually.
This PR integrates the arbitrary rotation and rescaling steps into the core atlas transformer to reduce this redundancy. The registration entry point has been left untouched, and future PRs will need to integrate this additional transformer functionality into this registration.
Highlights:
- The `flipud` parameter in the `atlas_refiner.transpose_img` atlas transposer function is now `flip` to allow flipping along any given axis
- …
=> Integrate more transformations into the atlas transformer

docs/release/release_v1.6.md, magmap/gui/visualizer.py, magmap/io/importer.py, magmap/settings/prefs_prof.py
Fixes #200.
Swaps out the TraitsUI `FileEditor` for the Pyface `FileDialog` and `DirectoryDialog` as recommended [here](https://stackoverflow.com/a/26170183/1911852). The Pyface versions appear to work more reliably for file selection.
A separate button is required for directory selection since there does not appear to be a single dialog that allows selecting both files and directories. This turns out to not be such an issue since separate MM import pathways are used for importing files vs directories, so I've taken advantage of these separate buttons to clarify their different behaviors with separate labels and tooltips.
For more intuitive behavior, the import file browser now accepts multiple paths instead of relying on auto-detecting related image files. The old behavior is still …
=> Fix browsing for files or directories

docs/release/release_v1.6.md, magmap/gui/plot_editor.py, magmap/gui/visualizer.py
Commit https://github.com/sanderslab/magellanmapper/commit/5c32b8449d6b8a5e3f1fa0ec2a2c8d22e8d8c291 introduced a regression where adjustments to Plot Editor images' opacity level were forgotten when scrolling through planes, fixe here.
Also, the image adjustment channel selector now uses radio buttons instead of a dropdown list to reduce the number clicks since the channel can be selected immediately instead of first opening the dropdown.
=> Fix restoring image adjustment opacity when scrolling through planes

docs/release/release_v1.6.md, magmap/io/np_io.py, magmap/io/sitk_io.py
Commit https://github.com/sanderslab/magellanmapper/commit/bbf6b0803fd3066f049346191b663713bbbad05a introduced a regression where multichannel SimpleITK images would be treated as single-channel images when updating them with a NumPy array. Keep the multichannel status based on the given SimpleITK image.
Additional fixes:
- Loading 2D/2D+channel images by adding a z-axis
- Avoids inadvertently overwriting the `config.labels_meta` module reference when setting up an image
=> Fix image loading

docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/register.py, magmap/cv/cv_nd.py, magmap/plot/plot_support.py, magmap/settings/config.py
This PR enhances and fixes image rotation in several ways:
- Plot Editor axes are transformed rather than rotating the underlying data
- The atlas transformer supports an alternative rescaling/resizing by changing the rotation rather than the underlying data
- Fixed a regression in preserving the original label identities when rescaling/resizing images and during degree rotation in the atlas transformer
=> Fix image rotation

docs/release/release_v1.6.md, magmap/atlas/labels_meta.py, magmap/plot/plot_support.py
The save figure function wraps the Matplotlib `savefig` with path finding and incorporating config settings. This RP adds:
- Support additional arguments directly to `savefig` through `kwargs`
- The extension can now contain a preceding `.` since it is often included with other functions, such as `os.path.splitext`
- Backup before saving can be turned off if desired (on by default) to avoid generating excessive files
- Parent directories are generated since otherwise `savefig` will generate an error, and the parents are presumably desired
Similarly to the backup change, labels reference files are no longer backed up when saving labels metadata if the file already exists. If so, the file will simply be assumed to be correct and will not be copied to avoid overwriting it.
=> Increase flexibility of the figure save wrapper

docs/release/release_v1.6.md, magmap/cv/chunking.py, magmap/cv/detector.py, magmap/cv/stack_detect.py, magmap/gui/roi_editor.py, magmap/gui/visualizer.py, magmap/io/export_rois.py, magmap/plot/plot_3d.py, magmap/plot/plot_support.py, magmap/settings/config.py
We're splitting out the blob changes from the classifier branch (#199) here for modularity and to integrate them sooner.
- Blob archives are backed up before overwriting
- Fixed saving additional blob columns
- Fixed blob accessors/setters
- Fixed blob detections in the GUI with no selected channels or loaded blobs but none in the ROI
- Fixed exporting ROIs
- Reduced debug messages during blob detection
=> Back up blob archives and fix saving blob columns

docs/conf.py, docs/index.rst, docs/release/index.md, docs/release/release_v1.5.md, docs/release/release_v1.6.md, setup.py
The [Furo](https://github.com/pradyunsg/furo) theme provides a minimalist and yet modern interface, including light/dark color support and the new table of contents entries for API docs. Switching to this themes will improve navigation and readability of our ReadTheDocs.
=> Change Sphinx docs theme to Furo

.github/dependabot.yml
Prevent alerts for custom built packages, which follow a separate release schedule.
=> Ignore custom packages in dependabot

clrstats/R/clrstats.R, docs/release/release_v1.6.md
The Clrstats model fitting function has given an error when extracting values into the basic results table, fixed here. Raw stats are also now printed to console for inspection. The grouping column can now also be customized through the new `SplitCol` environment setting, which can be set in a profile.
=> Fix model fitting

bin/sample_cmds_bash.ipynb, docs/conf.py, docs/index.rst, docs/load.md, docs/release/release_v1.6.md, magmap/io/np_io.py, magmap/settings/atlas_prof.py
Direct TIF support (ie without importing the file) is still in experimental stage, but here goes for a few more basic features:
- TIFs with the channel as the first axis are now loaded properly
- The Atlas Editor will downsample TIFs loaded this way since they are memory mapped and would reduce disk loading time when only a subset of data is requested
- TIF metadata may included `Rotate=<n>` values, which are now implemented through 90º rotation
=> More direct TIF loading support

.github/workflows/main.yml, docs/release/release_v1.6.md, magmap/cv/classifier.py, magmap/cv/cv_nd.py, magmap/plot/plot_3d.py, magmap/tests/test_cv_nd.py
Here's a round-up of several changes to the general computer vision library:
- Added a function to generate angled planes, which can be used to construct registration masks that do not fit a simple cuboid shape
- The CLAHE wrapper uses the nD implementation in Scikit-image now that it has been added
- The CI will run unit tests for the `detector` and `classifier` modules
- Small doc fixes
=> Round-up for general CV updates

docs/release/release_v1.6.md, magmap/io/export_regions.py, magmap/plot/plot_2d.py, magmap/plot/plot_support.py, magmap/settings/config.py
The ROI Editor has shown a border around the zoomed plot that corresponds to the plane shown in the overview plots. This border was inadvertently lost when turning off the axes frame, fixed here.
Additional plot-related (but otherwise miscellaneous) changes:
- Added a 2D plot task to generate category plots in Seaborn
- Plot Editor label names can be customized
- Labels level image generation defaults to using the globally set image if no image path is given
=> Fix missing ROI border

docs/release/release_v1.6.md, magmap/gui/atlas_editor.py, magmap/gui/plot_editor.py, magmap/gui/roi_editor.py, magmap/gui/verifier_editor.py, magmap/gui/visualizer.py, magmap/plot/plot_support.py
The main viewers (ROI, Atlas, and Verifier Editors) have Matplotlib listeners attached to handle keyboard shortcuts and other actions. When the editors are refreshed, the listeners are not automatically detached, however, causing them to continue to respond to user events. Saving plots with `ctrl/cmd-s`, for example, saves a separate file for each time the figure has been fully refreshed.
This PR stores the listeners in the underlying mixin class and disposes of them when closing/refreshing the figure. Another unrelated fix is to ensure that 2D planes are within the range of the image to avoid an error when displaying 2D images with certain layouts.
=> Fix stale editor listeners

docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/register.py, magmap/io/sitk_io.py, magmap/plot/plot_support.py
Large label IDs may be lost when applying an Elastix Transformix filter. As a workaround suggested [here](https://github.com/SuperElastix/SimpleElastix/issues/205#issuecomment-718852030), this PR maps the label identities to their indices in their unique array, which minimizes the chance of having large values. Defaults to turning off this feature to avoid applying it to non-label images, such as when repeating a transformation to multiple intensity images.
I've bundled a few additional changes:
- Docs fixes/clarifications for loading registered images and Matplotlib-based image rotation and label annotation
- SimpleITK-based image transformer now supports multiple flips and fixes 90 degree 2D image rotation
=> Fix changes to large label IDs during registration

clrstats/NAMESPACE, clrstats/R/clrstats.R, clrstats/R/jitter_plot.R, docs/release/release_v1.6.md
The Clrstats plot saver closes all graphics devices after plotting to ensure that devices are flushed and no stale devices persist, but this cleanup ends up closing the PyCharm R plugin and Quartz graphics devices. Plotting again causes the R plugin to crash, presumably since its graphics device no longer exists. This PR specifically retains these graphics devices during device closure.
Also bundled here:
- Added a basic `NAMESPACE` file to the package so that its functions are exported
- Fixed linear regression in the model fitting function when only one condition exists by removing this variable in these cases
=> Fix plotting in PyCharm in Clrstats

docs/release/release_v1.6.md, magmap/atlas/edge_seg.py, magmap/cv/cv_nd.py, magmap/io/df_io.py, magmap/io/export_regions.py, magmap/io/libmag.py, magmap/plot/plot_2d.py, magmap/stats/vols.py, magmap/tests/test_libmag.py
This PR is a round-up of several small changes:
- The atlas perimeter function accepts a thickness parameter
- The Matplotlib plot decorations wrapper takes x/y-tick modifications
- The `libmag.splice_before` function to splice a string before a substring is simpler, with fewer assumptions
=> Customize atlas edge thickness

docs/release/release_v1.6.md, magmap/gui/atlas_editor.py, magmap/gui/image_viewer.py, magmap/gui/plot_editor.py, magmap/gui/roi_editor.py, magmap/plot/plot_support.py, setup.py
The Plot Editor shows region labels on mouse hover when registered atlas labels are loaded with an image. This PR fixes several issues with label interactivity:
- Greatly speeds up label display by using [blitting](https://matplotlib.org/stable/tutorials/advanced/blitting.html) in Matplotlib
- The label's position relative to the mouse now fits within the plot across zoom. The label has changed its position relative to the mouse depending in turn on where the mouse is relative to the whole image, which tends to keep the label within the plot. This relative image position is no longer relevant to the label position when zooming into an image, however. Instead, the relative plot position is used so that the label tends to stay within the plot.
=> Speed up region labels interaction and fix placement during zoom

.github/workflows/main.yml
The `ubuntu-latest` platform for GitHub Actions CI recently updated to Ubuntu 22.04 (see https://github.com/actions/runner-images/issues/6399) and dropped support for Python 3.6 (https://github.com/actions/setup-python/issues/544#issuecomment-1332535877)
As inspired by this workaround (https://github.com/microsoft/responsible-ai-toolbox/pull/1838), use Ubuntu 20.04 only for Python 3.6 testing.
=> Run CI for Python 3.6 on Ubuntu 20.04 only

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/gui/image_viewer.py, magmap/gui/plot_editor.py, magmap/io/export_regions.py, magmap/io/libmag.py, magmap/io/sitk_io.py, magmap/io/sqlite.py, magmap/plot/colormaps.py, magmap/plot/plot_2d.py, magmap/plot/plot_support.py, magmap/tests/test_libmag.py
PR #317 applied blitting to improve performance of displaying region labels so that hovering over labels is more responsive. This update broke atlas label editing, however, as the plot does not update. This PR fixes this label editing while also extending blitting to the paint controls and pan/zoom controls to improve their interactivity.
One side-effect is that the edited colors appear somewhat muted when first drawn but subsequently brighten to full intensity when initiating another edit or figure redraw.
This RP also bundles a few other changes:
- The motion threshold setting no longer applies to pan and zoom to maintain their interactivity
- Added a `register.RegImgs` data class to manage related images during image registration tasks
- Many print statements on startup and loading an …
=> Extend blitting to speed up atlas label editing and image pan/zoom

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
PRs #317 and #335 introduced blitting operations in the Plot Editor. This PR follows up with several fixes:
- Fixed mouse press/release events when a blitter has not been set
- Fixed stale paint circle when moving the mouse outside of a plot or changing planes
- Mouse presses can trigger both coordinate and region label updates
Additionally, the mouse motion handler has had a long-standing issue where state is not updated until the end of the handler, which can cause rapidly successive events to use a stale state. Now motion events that are not filtered will update state immediately, which improves the event filter check and fixes a slight lag experienced during zoom direction change.
=> Clean up Plot Editor blitting implementation

docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/ontology.py, magmap/atlas/register.py, magmap/atlas/transformer.py, magmap/cv/chunking.py, magmap/cv/cv_nd.py, magmap/cv/detector.py, magmap/cv/segmenter.py, magmap/cv/stack_detect.py, magmap/gui/plot_editor.py, magmap/gui/roi_editor.py, magmap/gui/vis_3d.py, magmap/gui/visualizer.py, magmap/plot/plot_2d.py, magmap/plot/plot_support.py
NumPy aliases for generic data types have been deprecated and now give an error as of NumPy v1.24 (see https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations). This PR changes these references to the standard Python types (see https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations).
=> Fix errors on deprecated NumPy data type aliases

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
Double (right) clicking the ROI Editor redraws it, but the click also set the images for blitting as for panning or zooming and prevented the images from appearing in the redrawn image or to be drawn very faintly. Fixed here by filtering out double-click events for pan/zoom.
=> Fix blank image when double-clicking ROI Editor

docs/release/release_v1.6.md, magmap/cv/detector.py, magmap/cv/stack_detect.py, magmap/cv/verifier.py, magmap/io/export_regions.py, magmap/io/np_io.py, magmap/io/sitk_io.py
The inner padding may exceed the space of the ROI, particularly for 2D images since the z-plane only has one plane, leading to zero or negative sizes. Fixed here by clipping the inner padding dimensions so that the remaining size will be greater than 0 if possible.
=> Fix ROI padding for blob verification and match-based colocalization in 2D images

docs/release/release_v1.6.md, setup.py
Fixes #428 . PyQt5 v.5.15.8 appears to give a startup error, fixed by installing the prior version.
=> Workaround for Qt backend error with PyQt5 v5.15.8

setup.py
Increment version to include workaround for critical runtime error (#428).
=> Bump version to v1.6a3

docs/release/release_v1.6.md, envs/requirements.txt, envs/requirements_py36, envs/requirements_py37, setup.py
Restore support for Python 3.6-3.7 by pinning to commit before the package requires Python >= 3.8. Also, fix the package requirements listing for Python 3.6 to not use Git, consistent with the other requirements listings.
=> Pin BrainGlobe Atlas API to last version supporting Python <= 3.6

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/io/sitk_io.py
This PR fixes groupwise registration for updates to the atlas profile structure. Cropping is also now optional since it was for a specialized case, now only applied when a truncated labels image is present.
As mentioned in #438, the current SimpleITK/SimpleElastix release lost support for groupwise registration. See https://github.com/sanderslab/magellanmapper/issues/438#issuecomment-1420253006 for a potential workaround.
=> Fix profile access in groupwise registration

clrstats/R/clrstats.R, docs/cli.md, docs/release/release_v1.6.md, magmap/cv/verifier.py, magmap/io/export_regions.py, magmap/io/export_stack.py, magmap/plot/plot_2d.py, magmap/settings/config.py
Various fixes and small enhancements for data export:
- The `openpyxl` package is now optional for region CSV file export
- `--plot_labels rotation=<deg>` sub-argument to specify label rotation for 2D plots, supported in swarm and bar plot x-labels
- Options not to save 2D plots and to further customize swarm plots
- Stack export supports RGB images and removes TIF file extensions
- Blob verification matches logging is more readable
- Clrstats linear regression intercept term can be toggled via the new `config.env$Intercept <- FALSE` setting
- Easier to extract more stats from R models, such as `r<sup>2</sup>` and intercepts in linear regressions
=> Round up for customizing exports

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
The image opacity is typically generated from the image overlayer for multichannel images. This opacity displays correctly when first loading an image but is lost when scrolling through planes in the image, instead making all images fully opaque. This PR fixes the opacity by getting the alpha value from the displayed image in these cases.
=> Fix image opacity when scrolling through planes

bin/sample_cmds_bash.ipynb, docs/release/release_v1.6.md, magmap/cv/colocalizer.py, magmap/cv/verifier.py, magmap/gui/visualizer.py, magmap/io/cli.py
Match-based blob colocalization has run separate colocalizations for each pair of channels in the blobs archive, but one may wish to colocalize only select channels. This PR:
- Supports the `--channel <n> <n1> ...` CLI argument to specify the channels to colocalize. Note that all pairs within the given channels will be run.
- Refactored these colocalization functions to use the `Blobs` class as part of our ongoing effort to use pass these objects instead of just blobs array so as to include additional metadata
- Added Notebook docs on running colocalizations
=> Support selecting specific channels for match-based colocalization

docs/release/release_v1.6.md, magmap/cv/detector.py, magmap/gui/visualizer.py
Blobs archives added a metadata field for columns to indicate which columns are included in the archive (blobs format v4). Older archives without this metadata have been loaded as if they contained all columns, even though they often do not. This PR couples blob and blob column name attributes to ensure that blobs and column names are set together. Column names default to the fit the number of columns in the blobs array.
=> Fix blobs column setup for archives without columns metadata

docs/release/release_v1.6.md, docs/viewers.md, magmap/plot/plot_support.py
The shortcut has been to right-click on the ROI plane, but control-left-click can emulate a right-click, which conflicts with the same shortcut used to add a blob.
This PR changes the shortcut to "j"-left-click for "jump." Although this shortcut may not be as memorable, it is also less likely used since mouse scrolling and the arrow keys also control ROI plane scrolling. By preventing accidental jumping, the ROI is less likely to shift unexpectedly when viewing the next ROI.
=> Change shortcut for jumping to plane in ROI

docs/cli.md, docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/plot/plot_2d.py, magmap/settings/config.py
This PR is another round-up of changes, focused on programmatic access.
Plot decorations have been applied in most 2D plot tasks, but these labels may be lost when adding additional plots such as those from Seaborn. Add a task specifically to (re)decorate these labels.
Also, the 2D plot task has been set through `config`, typically as a CLI argument. Add a parameter in the main 2D plotting entry point to set this task through the API.
Image registration `register.curate_img` is now public to make this post-processing more accessible.
=> Roundup to make 2D plot tasks and registration post-processing more accessible

docs/release/release_v1.6.md, magmap/plot/plot_support.py
Vertical span labels have been set in data limits, but the axes limits may differ from data limits, such as plots with error bars or violin plots. Changed this positioning to use axes-relative coordinates instead.
=> Position vertical span labels in axes coordinates

docs/release/release_v1.6.md, magmap/io/export_stack.py, magmap/plot/plot_2d.py, magmap/plot/plot_support.py
Fixes #452. 
Image rotation by affine transformations do not change the axes limits, which can crop images in some areas while leaving large gaps in others. Fixed here by adjusting the axes limits to fit a rotated image. For simplicity, the image is now rotated around the origin rather than the image center. The transformation is also no longer applied when no rotation is set.
This PR also includes additional fixes for fitting a figure frame to an image. Setting a tight layout in a figure that has been set to use a constrained layout leads to an error, for example when exporting a stack with a colorbar and setting a padding for the image. Fix here by setting the padding through the constrained layout engine if the figure has this engine.nn
Constrained layout also does not appear to allow …
=> Adapt axes bounding box to rotated image

docs/release/release_v1.6.md, magmap/gui/visualizer.py
Toggling channels in the "Adjust Image" panel has retrieved a currently displayed image and using its values to populate the panel's controls. Changing each of these controls in turn triggered additional image updates, though typically without changing the image since it already had these settings. Toggling the auto-intensity has similarly triggered an "update" to the current value. While this design has simplified the callbacks, it also leads to many unnecessary triggers. This PR reduces many of those triggers by ignoring many of these redundant events.
This PR also provides a workaround for #473, where one intensity sliders may shift unexpectedly and trigger a change in the other intensity slider. The workaround is simply to turn off this synchronization during intensity slider …
=> Reduce image adjustment triggers

README.md, docs/conf.py, docs/install.md, docs/release/release_v1.6.md, setup.py
Add the `Sphinx-autodoc-typehints` setting to output default arguments for function parameters next to type hints. This PR also serves as the release branch for v1.6b1.
=> Generate auto-docs with default function arguments

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/plot/plot_2d.py, magmap/plot/plot_support.py, magmap/stats/vols.py
This PR is a round-up that adds a couple options to the wrapper for generating scatter plots in Matplotlib. These settings extend similar functionality from the swarm plot wrapper in Seaborn to the scatter plot wrapper.
- `jitter` parameter to add "jitter" to point x-value positions, which helps distinguish overlapping points
- `rotation` parameter to rotate x-tick labels
- Fixed more NumPy references to data types now that these references have been removed from NumPy
- Matplotlib core fonts are set for PDF and PS export so text is editable without embedding font info
=> Generate jitter plots in Matplotlib

docs/release/release_v1.6.md, magmap/gui/atlas_editor.py, magmap/gui/plot_editor.py, magmap/gui/roi_editor.py, magmap/gui/verifier_editor.py, magmap/gui/visualizer.py, magmap/io/libmag.py, magmap/plot/colormaps.py, magmap/plot/plot_support.py, magmap/settings/config.py, magmap/settings/roi_prof.py
Multi-channel images have been shown with each channel overlaid on the next with progressively increasing levels of translucency. While this overlay is straightforward and can work well for a small number of colors, the colors become increasingly muted. As an alternative, colors can be blended in an additive manner to retain more signal from underlying layers of channels.
To implement this blending, we convert channels to a black-to-single-color colormap and take the maximum value across channels at each pixel, as inspired by the [microfilm](https://github.com/guiwitz/microfilm) package. Users can toggle this channel merging through a new check box, which dynamically updates the ROI and Atlas editor plots. The ROI Editors's zoom plots now use `PlotEditor` instances to store and update …
=> Add additive blending to merge channels

docs/release/release_v1.6.md, magmap/atlas/register.py, magmap/io/sitk_io.py, setup.py
Addresses #496. This PR is the first of a series of PRs to add support for the ITK-Elastix image registration library as an alternative to SimpleITK with Elastix.
Images can now be registered using ITK-Elastix instead of requiring a custom build of SimpleITK with Elastix enabled. Continues to require SimpleITK to load images, but can use the standard SimpleITK package available on PyPi instead of the custom build.
=> Support ITK-Elastix for image registration

docs/install.md, docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/atlas/register.py, magmap/io/export_regions.py, magmap/io/export_rois.py, magmap/io/libmag.py, magmap/io/np_io.py, magmap/io/sitk_io.py, magmap/settings/config.py, magmap/stats/atlas_stats.py, magmap/tests/test_libmag.py, setup.py
Addresses #496. This PR change SimpleITK from a required to an optional dependency. Equivalent support for most SimpleITK functionality has been implemented through ITK-Elastix. I/O operations have been moved into wrapper functions that support both libraries, while #495 added support to ITK-Elastix in image registration functions.
To determine which library to use, the following approach is applied:
- Functions that take an image as input determine the library based on the type of the image, either `sitk.Image` or `itk.Image`
- If a function does not take an image, the type of other objects is used if available, eg the Transformix filter in registration functions
- If no arguments are available to specify type, SimpleITK will be used if installed
- Otherwise, ITK will be used and assumed …
=> Make SimpleITK dependency optional

docs/release/release_v1.6.md, magmap/brain_globe/bg_controller.py, magmap/brain_globe/bg_model.py, magmap/gui/visualizer.py, setup.py
We currently install the BrainGlobe Atlas API from a pre-release Git commit to use a download progress handler, but PyPI does not allow packages that depend on these releases outside of PyPI. Here we fall back to allow the current Atlas API release, without a progress handler. When the handler is not available, the progress bar will not become a busy indicator to show an indeterminate but ongoing download. This change also benefits atlases that do not report their full download size for some reason. We also tweaked the progress bar message so that it should update more reliably and show the atlas being downloaded.
=> Use BrainGlobe Atlas API from PyPI

docs/release/release_v1.6.md, magmap/io/importer.py
Prevent error when objective section but magnification entry is not available or if no name tag is available during image import through Bio-Formats.
=> Fix import error when magnification or name is not available

docs/release/release_v1.6.md, magmap/plot/plot_support.py
PR #471 introduced a regression where the transformation data class was added as an argument to the Matplotlib text annotation when only the transform itself should be added. Add this transform only when both the data class instance and transform are present since a transform of None also appears to override any default transform.
=> Fix displaying atlas labels on rotated images

docs/release/release_v1.6.md, magmap/atlas/atlas_refiner.py, magmap/atlas/edge_seg.py, magmap/atlas/register.py, magmap/io/sitk_io.py
The spacing object must be cast to a standard sequence before reversal.
=> Fix reversing image spacing for images loaded by ITK

magmap/cv/colocalizer.py
Change this parameter to its replacement, `footprint` (see Scikit-image[ v0.20 release notes](https://scikit-image.org/docs/dev/release_notes/release_0.20.html#completed-deprecations)).
=> Fix removal of `selem` parameter in Scikit-image v0.20

.github/workflows/main.yml, docs/release/release_v1.6.md
The CI has been testing pinned dependencies using the current `requirements.txt` file. Dependency packages are cached, updated only when this file changes, and updated to the specific versions of all dependencies in this file. While this setup reduces time CI setup time, it does not test updates to the latest dependency updates that may cause installation breakages, such as those addressed in #431 and #510.
This PR test these latest dependencies by adding a CI setup configuration for "fresh" dependencies. In this setup, Pip skips the cache and installs the current dependency versions rather than using `requirements.txt`. Installation without any install groups has fewer dependencies than `requirements.txt` does since requirements has dependencies from extra install groups. Without these …
=> Test fresh dependencies in CI

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
Commit b754375e3cca72f1da1d8a407e93675cd3d59b80 introduced a regression where alpha values would repeatedly be appended to a single list instead of creating a new list each time a new image was shown, fixed here.
=> Fix remembering the labels image opacity

.readthedocs.yaml, docs/conf.py, docs/install.md, docs/release/release_v1.6.md
#559 did not update the ReadTheDocs documentation configuration to use Python 3.9, which is required to build the docs environment using the existing `requirements.txt` file.
=> Fix ReadTheDocs for Python 3.9

docs/install.md, docs/release/release_v1.6.md, magmap/gui/visualizer.py
The adjustment sliders have attempted to adapt to the majority of signal in the image to increase precision of slider adjustments by limiting the range. The full range is sometimes necessary, however, to obtain the optimal viewing intensity. The workaround has been to manually enter values into the intensity text boxes.
This PR changes the sliders to the TraitsUI large range mode, which adds additional button to navigate to smaller or larger ranges. Remove the automated limit adjustments since the full range can now be navigated. The auto-intensity still attempts to select an appropriate starting intensity, which also positions the slider in an appropriate starting slider range. Additionally, reduce the number of decimal points in slider values and size of names since the large range …
=> Extend image adjustment sliders to use full intensity range

docs/release/release_v1.6.md, magmap/gui/visualizer.py, magmap/settings/prefs_prof.py
Save the path to images loading through the GUI, whether through the image open button or by simply updating the image path. Initialize the file open dialog to this path's parent directory in a new session.
=> Store the last opened image via the GUI in preferences

docs/release/release_v1.6.md, magmap/gui/visualizer.py, magmap/io/np_io.py, magmap/plot/colormaps.py
Colormaps have been customized using ROI profiles, but there has been no way to directly change colormaps through the GUI. This PR adds a searchable selector in the image adjustment panel to select a colormap for each channel, dynamically updating the image with the selected colormap. Available colormaps are all those in Matplotlib plus the custom dark-to-color maps generated in MM.
=> Select colormaps in the GUI

bin/sample_cmds_bash.ipynb, magmap/atlas/reg_tasks.py
Labels difference images have been generated from the R pipeline output. Now, these images can be generated directly from the volume metrics output. In this case, the values are typically for a single sample, with the metric specified by `--plot_labels x_col=<column>`, producing a regional heat map.
=> Support generating regional heat maps from the volume metrics output

docs/release/release_v1.6.md, magmap/settings/roi_prof.py
Block processing uses the same blocks for all channels if all the relevant settings for the block are the same across these channels. The tolerance factor verification setting has been checked but does not influence the block's processing, so it can be removed from this settings check.
=> Remove `verify_tol_factor` from identical block settings check

docs/release/release_v1.6.md, magmap/gui/visualizer.py
Although the data type may allow negative values, these values are often not used in images and may create confusion in the image sliders. Exclude these values by default, unless the image's precalculated near minimum is negative.
=> Exclude negative intensities by default in image sliders

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
Alpha blending sets the image's alpha to an array, which leads to an error when turning off alpha blending and comparing the array to a scalar. As a workaround, manually reset the current alpha to avoid an error during this comparison.
=> Workaround Matplotlib error when turning off alpha blending

.github/workflows/main.yml, README.md, bin/setup_venv.sh, docs/install.md, docs/pipelines.md, docs/release/release_v1.6.md, envs/requirements.txt, magmap/atlas/ontology.py, magmap/gui/visualizer.py, setup.py
The GUI has not worked in Python 3.12, fixed here.
Note that ITK does not currently provide binaries for Python 3.12, so the install group for it needs to be excluded for now. Install MM with only the GUI:
```
pip install "magellanmapper[gui]"
```
=> Support Python 3.12

docs/release/release_v1.6.md, magmap/io/cli.py, magmap/plot/colormaps.py
Fixes access to Matplotlib colormaps from the deprecated `cm.get_cmap` to the `colormaps[<name>]` API. Also fixes CLI slice arguments such as `--slice 0,3` to not convert `0` to `None`.
=> Fix Matplotlib colormap access

docs/release/release_v1.6.md, magmap/cv/detector.py, magmap/cv/stack_detect.py, magmap/gui/vis_3d.py, magmap/gui/visualizer.py, magmap/io/np_io.py, profiles/roi_blobs.yaml
3D blobs have been shown for ROIs but not for specific regions. Now selecting a region in the "Atlases" panel will display these blobs for just the selected region. This will occur when a blobs file has been loaded, and any blob channels are selected in the "Detect" panel.
To support these changes, the `Blobs` class has been undergoing cleanup to generalize access to different columns and adding new ones.
- The `Raw` 3D option is now off by default since users are most likely showing 3D regions instead of 3D ROIs
- Feedback from the regions control is displayed in the same panel rather than in the "ROI" panel
- Reloaded a saved ROI will no longer run detection in surrounding areas to avoid confusion about what blobs came from where
- Blobs archive version bumped to v5 …
=> Show 3D blobs by region

docs/release/release_v1.6.md, magmap/gui/plot_editor.py
Matplotlib v3.9.0 introduced a change wither `Line2D` x/y positions must be set with a sequence (see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#line2d), fixed here.
=> Fix crosshairs for Matplotlib v3.9.0

docs/release/release_v1.6.md, magmap/cv/detector.py
NumPy v2 has just been released, bringing many changes to the API, including the `np.lib` subpackage (see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-lib-namespace). Fix a reference to the `np.lib.index_tricks` module.
=> Fix for NumPy v2 release

magmap/io/export_regions.py, magmap/plot/colormaps.py
Region names can be exported along with their RGB colors, but these values were incorrect for region IDs that included corresponding positive and negative values. The RGB values are fixed here, along with support for generating this export in NumPy v2.
=> Fix exporting regions' RGB colors

bin/sample_cmds_bash.ipynb, docs/release/release_v1.6.md, magmap/io/cli.py
Adds navigation links by using anchors tags. This navigation currently only works on viewers such as this:
https://nbviewer.org/github/sanderslab/magellanmapper/blob/cleanup_notebook/bin/sample_cmds_bash.ipynb
In the GitHub viewer, the links apparently do not work because the page is shown within an iframe, and the links simply open the parent folder in the GitHub repo navigator.
=> Add navigation to the sample commands Jupyter Notebook

docs/release/release_v1.7.md, magmap/atlas/transformer.py, magmap/io/importer.py, magmap/io/np_io.py
MM can open TIF files without prior import using the `Tifffile` package. This PR allows exporting the opened TIF file to NPY format, which serves a couple purposes:
- TIF can be imported to NPY without using Javabridge/Bioformats
- Metadata in the resulting imported file can be modified without changing the original TIF file
The TIF will only be exported if the CLI flag `--savefig npy` is set. Note also that the save step is itself fast, but the near-intensity value calculation can be slower (eg increased save time from 1s to 4s). The new `write_npy` function has an option to turn off this calculation, but not currently accessible to the user.
The image resolution metadata is typically extracted when loading the TIF file but would give an error if missing. This PR now tolerates this …
=> Option to import TIF files to NPY format without Javabridge

docs/release/release_v1.7.md, magmap/plot/plot_2d.py
Shared axes, such as twin axes that share the same y-axis in a plot, only have the first axis updated with the post-plot and plot decoration functions. This PR finds the shared axes and updates all of them.
=> Fix applying settings across shared axes

docs/release/release_v1.7.md, magmap/io/df_io.py, magmap/plot/plot_2d.py
Default to keeping all columns and add an option to output to new columns to avoid overwriting the existing columns.
Also, reset the index in swarm plots to avoid errors with any existing index.
=> Simplify normalizing a data frame from a specific condition

.github/workflows/main.yml, docs/release/release_v1.7.md, magmap/cv/classifier.py, magmap/cv/stack_detect.py, magmap/gui/visualizer.py, magmap/io/cli.py, magmap/io/export_stack.py, magmap/io/importer.py, magmap/io/np_io.py, magmap/settings/config.py, magmap/stats/atlas_stats.py, magmap/tests/test_image_stack_integration.py, magmap/tests/unit_testing.py
Images have been stored in MM as direct NumPy arrays stored in the `config` module, with metadata stored as additional `config` attributes. One impact of this approach is that MM has largely only supported one loaded image per MM session. To encapsulate images, we previously introduced the `Image5d` class. This PR seeks to use this class as a replacement for the `config.image5d` reference. The image is still stored as a single `config.img5d` reference instead, with future PRs needed to expand MM to support multiple loaded images in the same instance.
- Image metadata is stored in the object when loaded
- Fixed more TIF loading issues
- Fixed blob detections when channels are not set up
- Fixed unit tests for loading images
=> Refactor image references to use `Image5d`
